# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
    auto_detect_solc = false
    bytecode_hash = "none"
    cache_path = "cache/foundry"
    cbor_metadata = false
    evm_version = "paris" # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
    gas_reports = ["*"]
    libs = [
        # We provide a set of useful contract utilities
        # in the lib directory of @layerzerolabs/toolbox-foundry:
        # 
        # - forge-std
        # - ds-test
        # - solidity-bytes-utils
        "node_modules/@layerzerolabs/toolbox-foundry/lib",
        "node_modules",
    ]
    optimizer = true
    optimizer_runs = 200
    out = "out"
    remappings = [
        # Due to a misconfiguration of solidity-bytes-utils, an outdated version
        # of forge-std is being dragged in
        # 
        # To remedy this, we"ll remap the ds-test and forge-std imports to ou own versions
        "ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test",
        "forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std",
        "@layerzerolabs/=node_modules/@layerzerolabs/",
        "@openzeppelin/=node_modules/@openzeppelin/",
    ]
    script = "scripts/foundry"
    solc = "0.8.22"
    src = "contracts"
    test = "test/foundry"

[doc]
    ignore = ["**/*.t.sol"]
    out = "docs"

[fmt]
    bracket_spacing = true
    int_types = "long"
    line_length = 120
    multiline_func_header = "all"
    number_underscore = "thousands"
    quote_style = "double"
    tab_width = 4
    wrap_comments = true
